FROM node:20-alpine AS build

WORKDIR /app

# Instalar dependências
COPY package.json yarn.lock ./
RUN yarn install

# Copiar arquivos necessários para o build do frontend
COPY index.html ./
COPY public ./public
COPY src ./src
COPY tailwind.config.js postcss.config.js ./
COPY tsconfig.json tsconfig.app.json tsconfig.node.json ./
COPY vite.config.ts ./

# Build do frontend
RUN yarn build

# Imagem final do Nginx servindo os arquivos estáticos
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

